[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "malware_analysis"
readme = "README.md"
dynamic = [ "dependencies", "version",]

[project.scripts]
malware-analysis = "malware_analysis.__main__:main"

[project.optional-dependencies]
docs = [ "docutils<0.21", "sphinx>=5.3,<7.3", "sphinx_rtd_theme==2.0.0", "nbsphinx==0.8.1", "sphinx-autodoc-typehints==1.20.2", "sphinx_copybutton==0.5.2", "ipykernel>=5.3, <7.0", "Jinja2<3.2.0", "myst-parser>=1.0,<2.1",]

[tool.kedro]
package_name = "malware_analysis"
project_name = "malware-analysis"
kedro_init_version = "0.19.7"
tools = [ "Linting", "Custom Logging", "Data Structure", "Documentation", "Kedro Viz",]
example_pipeline = "True"
source_dir = "src"

[tool.ruff]
line-length = 88
show-fixes = true
select = [ "F", "W", "E", "I", "UP", "PL", "T201",]
ignore = [ "E501",]

[project.entry-points."kedro.hooks"]

[tool.ruff.format]
docstring-code-format = true

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"

[tool.setuptools.dynamic.version]
attr = "malware_analysis.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false

[tool.kedro_telemetry]
project_id = "d137bf6c64994a68baa97a3696b35655"
